services:
  ### Discovery Server
  discovery-server:
    hostname: discovery-server
    container_name: discovery-server
    build:
      context: .
      dockerfile: ./discovery-server/Dockerfile
    #image: georgegxx/discovery-server:latest
    env_file:
      - .env
    ports:
      - ${DISCOVERY_PORT}:${DISCOVERY_PORT}
    restart: unless-stopped
    networks:
      - spring
  
  ### Keycloak
  keycloak:
    hostname: keycloak
    container_name: keycloak
    image: "quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}"
    command: [ "start-dev" ]
    restart: unless-stopped
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    # expose:
    #   - 8181
    depends_on:
      - db-keycloak
    env_file:
      - .env
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${KEYCLOAK_POSTGRES_DB}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: ${KC_HTTP_PORT}
    networks:
      - spring
  ### Posgres database for Keycloak
  db-keycloak:
    hostname: db-keycloak
    container_name: db-keycloak
    image: "postgres:${KEYCLOAK_POSTGRES_VERSION}"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - keycloak-pgdata:/var/lib/postgresql/data
    ports:
      - "5434:${POSTGRES_PORT}"
    networks:
      - spring
    # expose:
    #   - 5434
    # command: -p 5434

  ### API Gateway
  api-gateway:
    hostname: api-gateway
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    env_file:
      - .env
    environment:
      DISCOVERY_URL: ${DISCOVERY_URL}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}    
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    restart: unless-stopped
    networks:
      - spring

  ### Inventory Service
  inventory-service:
    hostname: inventory-service
    container_name: inventory-service
    build:
      context: .
      dockerfile: ./inventory-service/Dockerfile
    env_file:
      - .env
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
    # ports:
    #   - ${PORT}:${PORT}
    restart: unless-stopped
    depends_on:
      - discovery-server
      - kafka
      - db-inventory
    networks:
      - spring
  ### Postgres database for inventory
  db-inventory:
    hostname: db-inventory
    container_name: db-inventory
    image: "postgres:${POSTGRES_VERSION}"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - inventory-pgdata:/var/lib/postgresql/data
    ports:
      - "5431:${POSTGRES_PORT}"
    networks:
      - spring
    # expose:
    #   - 5431
    # command: -p 5431

  ### Notification Service
  notification-service:
    hostname: notification-service
    container_name: notification-service
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    env_file:
      - .env
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
    # ports:
    #   - ${PORT}:${PORT}
    restart: unless-stopped
    depends_on:
      - discovery-server
      - kafka
    networks:
      - spring

  ### Orders Service
  orders-service:
    hostname: orders-service
    container_name: orders-service
    build:
      context: .
      dockerfile: ./orders-service/Dockerfile
    env_file:
      - .env
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
    # ports:
    #   - ${PORT}:${PORT}
    restart: unless-stopped
    depends_on:
      - discovery-server
      - kafka
      - db-orders
    networks:
      - spring
  ### MySQL database for orders
  db-orders:
    hostname: db-orders
    container_name: db-orders
    image: "mysql:${MYSQL_VERSION}"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - orders-mydata:/var/lib/mysql
    ports:
      - "3307:${MYSQL_PORT}"
    networks:
      - spring
    # expose:
    #   - 3307

  ### Products Service
  products-service:
    hostname: products-service
    container_name: products-service
    build:
      context: .
      dockerfile: ./products-service/Dockerfile
    env_file:
      - .env
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
    # ports:
    #   - ${PORT}:{PORT}
    restart: unless-stopped
    depends_on:
      - discovery-server
      - kafka
      - db-products
    networks:
      - spring
  ### Postgres database for products
  db-products:
    hostname: db-products
    container_name: db-products
    image: "postgres:${PRODUCTS_POSTGRES_VERSION}"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PRODUCTS_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - products-pgdata:/var/lib/postgresql/data
    ports:
      - "5433:${POSTGRES_PORT}"
    networks:
      - spring
    # expose:
    #   - 5433
    # command: -p 5433

  ### Kafka Broker
  kafka:
    hostname: kafka
    container_name: kafka
    image: "confluentinc/cp-kafka:${KAFKA_VERSION}"
    restart: unless-stopped
    depends_on:
      - zookeeper
    # ports:
    #   - "${KAFKA_PORT}:${KAFKA_PORT}"
    #   - "${KAFKA_INTERNAL_PORT}:${KAFKA_INTERNAL_PORT}"
    networks:
      - spring
    env_file:
      - .env
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_LOG_DIRS: ${KAFKA_LOG_DIRS}
    volumes:
      - kafka_data:/var/lib/kafka/data

  ### ZooKeeper
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: "confluentinc/cp-zookeeper:${ZOOKEEPER_VERSION}"
    restart: unless-stopped
    networks:
      - spring
    env_file:
      - .env
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
      ZOOKEEPER_DATA_DIR: ${ZOOKEEPER_DATA_DIR}
      ZOOKEEPER_DATA_LOG_DIR: ${ZOOKEEPER_DATA_LOG_DIR}
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
#      - "6379:6379"
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.37
    container_name: jaeger
    ports:
#      - "16686:16686" # UI
#      - "14250:14250" # Collector gRPC
      - "${JAEGER_UI_PORT}:${JAEGER_UI_PORT}" # UI
      - "${JAEGER_COL_PORT}:${JAEGER_COL_PORT}" # Collector gRPC
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel/config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    ports:
      #      - "4317:4317"   # OTLP gRPC
      #      - "4318:4318"   # OTLP HTTP
      - "${OTEL_GRCP_PORT}:${OTEL_GRCP_PORT}" # OTLP gRPC
      - "${OTEL_HTTP_PORT}:${OTEL_HTTP_PORT}" # OTLP HTTP
    depends_on:
      - jaeger

volumes:
  inventory-pgdata:
  orders-mydata:
  products-pgdata:
  keycloak-pgdata:
  kafka_data:
  redis_data:

networks:
  spring: