apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
    - port: 8002
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: your-dockerhub/notification-service:latest
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: microservices-config
            - secretRef:
                name: microservices-secrets
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: ${OTEL_EXPORTER_OTLP_ENDPOINT}
#              value: "http://otel-collector:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=products-service"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8002
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8002
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10  
