spring.application.name=${PRODUCTS_SERVICE_NAME}
server.port=${PORT:0}
#server.port=0

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${PRODUCTS_SPRING_DATASOURCE_JDBC_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
#spring.datasource.url=jdbc:postgresql://localhost:5433/ms_products
#spring.datasource.username=postgres
#spring.datasource.password=admin

#Eureka client
eureka.client.service-url.defaultZone=${DISCOVERY_AUTH_URL}
#eureka.client.service-url.default-zone=http://eureka:password@localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

# Keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWT_URI}
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/microservices-realm/protocol/openid-connect/certs

# Actuator
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/actuator/products

# Otel
management.tracing.enabled=true
# si usas bridge y exporter en app:
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
#management.otlp.tracing.endpoint=http://otel-collector:4317
#management.otlp.traces.endpoint=http://otel-collector.default.svc.cluster.local:4317
management.tracing.sampling.probability=1.0
# service name (si no lo pones, agent puede inferirlo)
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
#otel.resource.attributes=service.name=my-service,service.version=1.0
otel.resource.attributes=service.name=${PRODUCTS_SERVICE_NAME},service.version=1.0

# Redis
#spring.cache.type=${REDIS_HOST}
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}